export enum ErrorCode {
  // Auth errors
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_BLOCKED = 'USER_BLOCKED',
  INVALID_TOKEN = 'INVALID_TOKEN',
  
  // Data errors
  INVALID_DATA = 'INVALID_DATA',
  ENTITY_NOT_FOUND = 'ENTITY_NOT_FOUND',
  DUPLICATE_ENTRY = 'DUPLICATE_ENTRY',
  
  // Payment errors
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  INVALID_CARD = 'INVALID_CARD',
  
  // System errors
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
}
